name: Github Page
# https://www.cnblogs.com/missile/p/13821397.html
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false


      - name:  Config
        run: |
          rm .env.production
          mv files/github_.env.production .env.production
          rm vue.config.js
          mv files/github_vue.config.js vue.config.js

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: | #æ³¨æ„æˆ‘è¿™é‡Œæ˜¯ä½¿ç”¨çš„yarnç®¡ç†åŒ…ï¼Œå¦‚æœä½ ä½¿ç”¨çš„npmï¼Œè¯·æ¢æˆnpmçš„å‘½ä»¤ï¼šnpm installå’Œnpm run build
          npm install
          npm install vue-recaptcha-v3@^1.9.0
          npm install --save @tinymce/tinymce-vue@^3
          npm install tinymce
          npm run build:prod

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} #secrets.ACCESS_TOKENæ˜¯é¡¹ç›®é…ç½®çš„å¯†é’¥
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
